package com.hydroyura.prodms.files.server.props;


import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "minio")
@Data
public class MinioProps {

    private String url;
    private String accessKey;
    private String accessSecret;
    private String cert = """
-----BEGIN CERTIFICATE-----
MIIDXzCCAkegAwIBAgIRAIBdXsFNm2md8pnqcnAYcicwDQYJKoZIhvcNAQELBQAw
FTETMBEGA1UEAxMKbWluaWt1YmVDQTAeFw0yNTAxMjIwNjUxMzRaFw0yNjAxMjIw
NjUxMzRaMF4xFTATBgNVBAoTDHN5c3RlbTpub2RlczFFMEMGA1UEAww8c3lzdGVt
Om5vZGU6Ki5wcm9kbXMtbWluaW8taGwucHJvZG1zLWluZnJhLnN2Yy5jbHVzdGVy
LmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEDdRY34IJzGgEM2GAjHiU
SwzNrbrEC5Z8xJSvc1lFcrCiEtjquNamlIXD+RGLsYtQ/5KrZYuYGHFrrA0Gin0Q
OaOCASowggEmMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAM
BgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFF6PGFq8r++0UvlHLChZv9ftfDMFMIHP
BgNVHREEgccwgcSCSnByb2Rtcy1taW5pby1taW5pby1wb29sLTAtMC5wcm9kbXMt
bWluaW8taGwucHJvZG1zLWluZnJhLnN2Yy5jbHVzdGVyLmxvY2FsgiRtaW5pby5w
cm9kbXMtaW5mcmEuc3ZjLmNsdXN0ZXIubG9jYWyCEm1pbmlvLnByb2Rtcy1pbmZy
YYIWbWluaW8ucHJvZG1zLWluZnJhLnN2Y4ICKi6CICoucHJvZG1zLWluZnJhLnN2
Yy5jbHVzdGVyLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQAI97k1egbwpFm5SoZt
8M4vdS75r2ATgA7N+leauhaOupfNDYhlgJ7vCdSOqHMFj6OfoNlCW0QFSVJSy5a3
vf5lVLgVcfRecRZLErII58ZHtUgPjwPF7xoPj1GMyNaD9DPKR8HK/kRvGXq3G1t0
6E+VpJ+pO62H17y+sUPrWFY3Z3Ko7lGoevbCMqeMceRT3hgvgNJ3HS7VMllLMhTX
83Al+mhenJozSwUCHHwBnLSXf8fUwjaoKf2MtMcaP9YkaImzNUGlS+Kkr0k9q86M
OHvs6GEVz6eAq1m8DGZVwOJwrI+PbNdclscwaKddBetfvevvMS9JRSfjN9jLWFKg
Zzmq
-----END CERTIFICATE-----""";

}
